apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zeebes.helm.operator-sdk
spec:
  group: helm.operator-sdk
  names:
    kind: Zeebe
    listKind: ZeebeList
    plural: zeebes
    singular: zeebe
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
