apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zeebeclusters.charts.helm.k8s.io
spec:
  group: charts.helm.k8s.io
  names:
    kind: ZeebeCluster
    listKind: ZeebeClusterList
    plural: zeebeclusters
    singular: zeebecluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
