apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeebe-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zeebe-operator
  template:
    metadata:
      labels:
        name: zeebe-operator
    spec:
      serviceAccountName: zeebe-operator
      containers:
        - name: zeebe-operator
          # Replace this with the built image name
          image: gcr.io/codelity-co/zeebe-operator:v0.3.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "zeebe-operator"
